# deploy.yml
name: dev branch auto ci process script

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.10 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/mini_todo_cicd
            git pull origin main
            pm2 delete mini_todo
            npm install
            pm2 start app.js --name "mini_todo"
